/*
 Highcharts JS v6.0.3 (2017-11-14)
 Old IE (v6, v7, v8) module for Highcharts v6+.

 (c) 2010-2017 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(l){"object"===typeof module&&module.exports?module.exports=l:l(Highcharts)})(function(l){(function(d){var u,g;g=d.Chart;var A=d.createElement,l=d.css,E=d.defined,t=d.deg2rad,F=d.discardElement,h=d.doc,J=d.each,G=d.erase,B=d.extend;u=d.extendClass;var M=d.isArray,H=d.isNumber,C=d.isObject,N=d.merge,K=d.noop,y=d.pick,n=d.pInt,O=d.svg,v=d.SVGElement,w=d.SVGRenderer,x=d.win,P=d.wrap;d.getOptions().global.VMLRadialGradientURL="http://code.highcharts.com/6.0.3/gfx/vml-radial-gradient.png";h&&
!h.defaultView&&(d.getStyle=function(a,b){var c={width:"clientWidth",height:"clientHeight"}[b];if(a.style[b])return d.pInt(a.style[b]);"opacity"===b&&(b="filter");if(c)return a.style.zoom=1,Math.max(a[c]-2*d.getStyle(a,"padding"),0);a=a.currentStyle[b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()})];"filter"===b&&(a=a.replace(/alpha\(opacity=([0-9]+)\)/,function(a,b){return b/100}));return""===a?1:d.pInt(a)});Array.prototype.forEach||(d.forEachPolyfill=function(a,b){for(var c=0,e=this.length;c<
e;c++)if(!1===a.call(b,this[c],c,this))return c});Array.prototype.indexOf||(d.indexOfPolyfill=function(a){var b,c=0;if(a)for(b=a.length;c<b;c++)if(a[c]===this)return c;return-1});Array.prototype.filter||(d.filterPolyfill=function(a){for(var b=[],c=0,e=this.length;c<e;c++)a(this[c],c)&&b.push(this[c]);return b});Object.prototype.keys||(d.keysPolyfill=function(a){var b=[],c=Object.prototype.hasOwnProperty,e;for(e in a)c.call(a,e)&&b.push(e);return b});Array.prototype.reduce||(d.reducePolyfill=function(a,
b){b=b||{};for(var c=this.length,e=0;e<c;++e)b=a.call(this,b,this[e],e,this);return b});O||(P(d.SVGRenderer.prototype,"text",function(a){return a.apply(this,Array.prototype.slice.call(arguments,1)).css({position:"absolute"})}),d.Pointer.prototype.normalize=function(a,b){a=a||x.event;a.target||(a.target=a.srcElement);b||(this.chartPosition=b=d.offset(this.chart.container));return d.extend(a,{chartX:Math.round(Math.max(a.x,a.clientX-b.left)),chartY:Math.round(a.y)})},g.prototype.ieSanitizeSVG=function(a){return a=
a.replace(/<IMG /g,"\x3cimage ").replace(/<(\/?)TITLE>/g,"\x3c$1title\x3e").replace(/height=([^" ]+)/g,'height\x3d"$1"').replace(/width=([^" ]+)/g,'width\x3d"$1"').replace(/hc-svg-href="([^"]+)">/g,'xlink:href\x3d"$1"/\x3e').replace(/ id=([^" >]+)/g,' id\x3d"$1"').replace(/class=([^" >]+)/g,'class\x3d"$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(a){return a.toLowerCase()})},h.createElementNS||(h.createElementNS=function(a,b){return h.createElement(b)}),
d.addEventListenerPolyfill=function(a,b){function c(a){a.target=a.srcElement||x;b.call(e,a)}var e=this;e.attachEvent&&(e.hcEventsIE||(e.hcEventsIE={}),b.hcKey||(b.hcKey=d.uniqueKey()),e.hcEventsIE[b.hcKey]=c,e.attachEvent("on"+a,c))},d.removeEventListenerPolyfill=function(a,b){this.detachEvent&&(b=this.hcEventsIE[b.hcKey],this.detachEvent("on"+a,b))},g={docMode8:h&&8===h.documentMode,init:function(a,b){var c=["\x3c",b,' filled\x3d"f" stroked\x3d"f"'],e=["position: ","absolute",";"],d="div"===b;("shape"===
b||d)&&e.push("left:0;top:0;width:1px;height:1px;");e.push("visibility: ",d?"hidden":"visible");c.push(' style\x3d"',e.join(""),'"/\x3e');b&&(c=d||"span"===b||"img"===b?c.join(""):a.prepVML(c),this.element=A(c));this.renderer=a},add:function(a){var b=this.renderer,c=this.element,e=b.box,d=a&&a.inverted,e=a?a.element||a:e;a&&(this.parentGroup=a);d&&b.invertChild(c,e);e.appendChild(c);this.added=!0;this.alignOnAdd&&!this.deferUpdateTransform&&this.updateTransform();if(this.onAdd)this.onAdd();this.className&&
this.attr("class",this.className);return this},updateTransform:v.prototype.htmlUpdateTransform,setSpanRotation:function(){var a=this.rotation,b=Math.cos(a*t),c=Math.sin(a*t);l(this.element,{filter:a?["progid:DXImageTransform.Microsoft.Matrix(M11\x3d",b,", M12\x3d",-c,", M21\x3d",c,", M22\x3d",b,", sizingMethod\x3d'auto expand')"].join(""):"none"})},getSpanCorrection:function(a,b,c,e,d){var f=e?Math.cos(e*t):1,p=e?Math.sin(e*t):0,q=y(this.elemHeight,this.element.offsetHeight),D;this.xCorr=0>f&&-a;
this.yCorr=0>p&&-q;D=0>f*p;this.xCorr+=p*b*(D?1-c:c);this.yCorr-=f*b*(e?D?c:1-c:1);d&&"left"!==d&&(this.xCorr-=a*c*(0>f?-1:1),e&&(this.yCorr-=q*c*(0>p?-1:1)),l(this.element,{textAlign:d}))},pathToVML:function(a){for(var b=a.length,c=[];b--;)H(a[b])?c[b]=Math.round(10*a[b])-5:"Z"===a[b]?c[b]="x":(c[b]=a[b],!a.isArc||"wa"!==a[b]&&"at"!==a[b]||(c[b+5]===c[b+7]&&(c[b+7]+=a[b+7]>a[b+5]?1:-1),c[b+6]===c[b+8]&&(c[b+8]+=a[b+8]>a[b+6]?1:-1)));return c.join(" ")||"x"},clip:function(a){var b=this,c;a?(c=a.members,
G(c,b),c.push(b),b.destroyClip=function(){G(c,b)},a=a.getCSS(b)):(b.destroyClip&&b.destroyClip(),a={clip:b.docMode8?"inherit":"rect(auto)"});return b.css(a)},css:v.prototype.htmlCss,safeRemoveChild:function(a){a.parentNode&&F(a)},destroy:function(){this.destroyClip&&this.destroyClip();return v.prototype.destroy.apply(this)},on:function(a,b){this.element["on"+a]=function(){var a=x.event;a.target=a.srcElement;b(a)};return this},cutOffPath:function(a,b){var c;a=a.split(/[ ,]/);c=a.length;if(9===c||11===
c)a[c-4]=a[c-2]=n(a[c-2])-10*b;return a.join(" ")},shadow:function(a,b,c){var e=[],d,f=this.element,L=this.renderer,q,D=f.style,k,r=f.path,g,m,h,l;r&&"string"!==typeof r.value&&(r="x");m=r;if(a){h=y(a.width,3);l=(a.opacity||.15)/h;for(d=1;3>=d;d++)g=2*h+1-2*d,c&&(m=this.cutOffPath(r.value,g+.5)),k=['\x3cshape isShadow\x3d"true" strokeweight\x3d"',g,'" filled\x3d"false" path\x3d"',m,'" coordsize\x3d"10 10" style\x3d"',f.style.cssText,'" /\x3e'],q=A(L.prepVML(k),null,{left:n(D.left)+y(a.offsetX,1),
top:n(D.top)+y(a.offsetY,1)}),c&&(q.cutOff=g+1),k=['\x3cstroke color\x3d"',a.color||"#000000",'" opacity\x3d"',l*d,'"/\x3e'],A(L.prepVML(k),null,null,q),b?b.element.appendChild(q):f.parentNode.insertBefore(q,f),e.push(q);this.shadows=e}return this},updateShadows:K,setAttr:function(a,b){this.docMode8?this.element[a]=b:this.element.setAttribute(a,b)},classSetter:function(a){(this.added?this.element:this).className=a},dashstyleSetter:function(a,b,c){(c.getElementsByTagName("stroke")[0]||A(this.renderer.prepVML(["\x3cstroke/\x3e"]),
null,null,c))[b]=a||"solid";this[b]=a},dSetter:function(a,b,c){var e=this.shadows;a=a||[];this.d=a.join&&a.join(" ");c.path=a=this.pathToVML(a);if(e)for(c=e.length;c--;)e[c].path=e[c].cutOff?this.cutOffPath(a,e[c].cutOff):a;this.setAttr(b,a)},fillSetter:function(a,b,c){var e=c.nodeName;"SPAN"===e?c.style.color=a:"IMG"!==e&&(c.filled="none"!==a,this.setAttr("fillcolor",this.renderer.color(a,c,b,this)))},"fill-opacitySetter":function(a,b,c){A(this.renderer.prepVML(["\x3c",b.split("-")[0],' opacity\x3d"',
a,'"/\x3e']),null,null,c)},opacitySetter:K,rotationSetter:function(a,b,c){c=c.style;this[b]=c[b]=a;c.left=-Math.round(Math.sin(a*t)+1)+"px";c.top=Math.round(Math.cos(a*t))+"px"},strokeSetter:function(a,b,c){this.setAttr("strokecolor",this.renderer.color(a,c,b,this))},"stroke-widthSetter":function(a,b,c){c.stroked=!!a;this[b]=a;H(a)&&(a+="px");this.setAttr("strokeweight",a)},titleSetter:function(a,b){this.setAttr(b,a)},visibilitySetter:function(a,b,c){"inherit"===a&&(a="visible");this.shadows&&J(this.shadows,
function(c){c.style[b]=a});"DIV"===c.nodeName&&(a="hidden"===a?"-999em":0,this.docMode8||(c.style[b]=a?"visible":"hidden"),b="top");c.style[b]=a},xSetter:function(a,b,c){this[b]=a;"x"===b?b="left":"y"===b&&(b="top");this.updateClipping?(this[b]=a,this.updateClipping()):c.style[b]=a},zIndexSetter:function(a,b,c){c.style[b]=a}},g["stroke-opacitySetter"]=g["fill-opacitySetter"],d.VMLElement=g=u(v,g),g.prototype.ySetter=g.prototype.widthSetter=g.prototype.heightSetter=g.prototype.xSetter,g={Element:g,
isIE8:-1<x.navigator.userAgent.indexOf("MSIE 8.0"),init:function(a,b,c){var e,d;this.alignedObjects=[];e=this.createElement("div").css({position:"relative"});d=e.element;a.appendChild(e.element);this.isVML=!0;this.box=d;this.boxWrapper=e;this.gradients={};this.cache={};this.cacheKeys=[];this.imgCount=0;this.setSize(b,c,!1);if(!h.namesp)"].join(""):"none"})},getSpanCorrection:function(a,b,c,e,d){var f=e?Math.cos(e*t):1,p=e?Math.sin(e*t):0,q=y(this.elemHeight,this.element.offsetHeight),D;this.xCorr=0>f&&-a;
this.yCorr=0>p&&-q;D=0>f*p;this.xCorr+=p*b*(D?1-c:c);this.yCorr-=f*b*(e?D?c:1-c:1);d&&"left"!==d&&(this.xCorr-=a*c*(0>f?-1:1),e&&(this.yCorr-=q*c*(0>p?-1:1)),l(this.element,{textAlign:d}))},pathToVML:function(a){for(var b=a.length,c=[];b--;)H(a[b])?c[b]=Math.round(10*a[b])-5:"Z"===a[b]?c[b]="x":(c[b]=a[b],!a.isArc||"wa"!==a[b]&&"at"!==a[b]||(c[b+5]===c[b+7]&&(c[b+7]+=a[b+7]>a[b+5]?1:-1),c[b+6]===c[b+8]&&(c[b+8]+=a[b+8]>a[b+6]?1:-1)));return c.join(" ")||"x"},clip:function(a){var b=this,c;a?(c=a.members,
G(c,b),c.push(b),b.destroyClip=function(){G(c,b)},a=a.getCSS(b)):(b.destroyClip&&b.destroyClip(),a={clip:b.docMode8?"inherit":"rect(auto)"});return b.css(a)},css:v.prototype.htmlCss,safeRemoveChild:function(a){a.parentNode&&F(a)},destroy:function(){this.destroyClip&&this.destroyClip();return v.prototype.destroy.apply(this)},on:function(a,b){this.element["on"+a]=function(){var a=x.event;a.target=a.srcElement;b(a)};return this},cutOffPath:function(a,b){var c;a=a.split(/[ ,]/);c=a.length;if(9===c||11===
c)a[c-4]=a[c-2]=n(a[c-2])-10*b;return a.join(" ")},shadow:function(a,b,c){var e=[],d,f=this.element,L=this.renderer,q,D=f.style,k,r=f.path,g,m,h,l;r&&"string"!==typeof r.value&&(r="x");m=r;if(a){h=y(a.width,3);l=(a.opacity||.15)/h;for(d=1;3>=d;d++)g=2*h+1-2*d,c&&(m=this.cutOffPath(r.value,g+.5)),k=['\x3cshape isShadow\x3d"true" strokeweight\x3d"',g,'" filled\x3d"false" path\x3d"',m,'" coordsize\x3d"10 10" style\x3d"',f.style.cssText,'" /\x3e'],q=A(L.prepVML(k),null,{left:n(D.left)+y(a.offsetX,1),
top:n(D.top)+y(a.offsetY,1)}),c&&(q.cutOff=g+1),k=['\x3cstroke color\x3d"',a.color||"#000000",'" opacity\x3d"',l*d,'"/\x3e'],A(L.prepVML(k),null,null,q),b?b.element.appendChild(q):f.parentNode.insertBefore(q,f),e.push(q);this.shadows=e}return this},updateShadows:K,setAttr:function(a,b){this.docMode8?this.element[a]=b:this.element.setAttribute(a,b)},classSetter:function(a){(this.added?this.element:this).className=a},dashstyleSetter:function(a,b,c){(c.getElementsByTagName("stroke")[0]||A(this.renderer.prepVML(["\x3cstroke/\x3e"]),
null,null,c))[b]=a||"solid";this[b]=a},dSetter:function(a,b,c){var e=this.shadows;a=a||[];this.d=a.join&&a.join(" ");c.path=a=this.pathToVML(a);if(e)for(c=e.length;c--;)e[c].path=e[c].cutOff?this.cutOffPath(a,e[c].cutOff):a;this.setAttr(b,a)},fillSetter:function(a,b,c){var e=c.nodeName;"SPAN"===e?c.style.color=a:"IMG"!==e&&(c.filled="none"!==a,this.setAttr("fillcolor",this.renderer.color(a,c,b,this)))},"fill-opacitySetter":function(a,b,c){A(this.renderer.prepVML(["\x3c",b.split("-")[0],' opacity\x3d"',
a,'"/\x3e']),null,null,c)},opacitySetter:K,rotationSetter:function(a,b,c){c=c.style;this[b]=c[b]=a;c.left=-Math.round(Math.sin(a*t)+1)+"px";c.top=Math.round(Math.cos(a*t))+"px"},strokeSetter:function(a,b,c){this.setAttr("strokecolor",this.renderer.color(a,c,b,this))},"stroke-widthSetter":function(a,b,c){c.stroked=!!a;this[b]=a;H(a)&&(a+="px");this.setAttr("strokeweight",a)},titleSetter:function(a,b){this.setAttr(b,a)},visibilitySetter:function(a,b,c){"inherit"===a&&(a="visible");this.shadows&&J(this.shadows,
function(c){c.style[b]=a});"DIV"===c.nodeName&&(a="hidden"===a?"-999em":0,this.docMode8||(c.style[b]=a?"visible":"hidden"),b="top");c.style[b]=a},xSetter:function(a,b,c){this[b]=a;"x"===b?b="left":"y"===b&&(b="top");this.updateClipping?(this[b]=a,this.updateClipping()):c.style[b]=a},zIndexSetter:function(a,b,c){c.style[b]=a}},g["stroke-opacitySetter"]=g["fill-opacitySetter"],d.VMLElement=g=u(v,g),g.prototype.ySetter=g.prototype.widthSetter=g.prototype.heightSetter=g.prototype.xSetter,g={Element:g,
isIE8:-1<x.navigator.userAgent.indexOf("MSIE 8.0"),init:function(a,b,c){var e,d;this.alignedObjects=[];e=this.createElement("div").css({position:"relative"});d=e.element;a.appendChild(e.element);this.isVML=!0;this.box=d;this.boxWrapper=e;this.gradients={};this.cache={};this.cacheKeys=[];this.imgCount=0;this.setSize(b,c,!1);if(!h.namespaces.hcv){h.namespaces.add("hcv","urn:schemas-microsoft-com:vml");try{h.createStyleSheet().cssText="hcv\\:fill, hcv\\:path, hcv\\:shape, hcv\\:stroke{ behavior:url(#default#VML); display: inline-block; } "}catch(f){h.styleSheets[0].cssText+=
"hcv\\:fill, hcv\\:path, hcv\\:shape, hc